name: Deploy to Live Server
on:
  push:
    branches:    
      - staging 

jobs:
  build:
    name: SSH Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /var/www/MukhlatV2
          git fetch origin
          git pull origin staging
          systemctl restart nginx